---
title: Community Science
---

Note: This site is currently under development.

## iNaturalist

I am an avid iNaturalist user, as an observer, identifier, and curator. I have a broad taxonomic focus while observing but a specific taxonomic focus (Cynipoidea) while identifying and curating taxonomy. I am the top identifier of Cynipoidea records in Canada on iNaturalist and have identified >75% of the Cynipoidea records in British Columbia.

iNaturalist is a particularly interesting species occurrence dataset due to the broad taxonomic and geographic scope of the platform. iNaturalist provides presence-only data, and includes no explicitly defined effort data, making it particularly unwieldy for biodiversity assessments and species distribution modelling. Despite its limitations, iNaturalist of proving to be an excellent resource for identifying the where and when of species.

See my [iNaturalist profile](https://inaturalist.ca/people/earley_bird).

## eBird

I have been a keen user of eBird for nearly a decade. I have birded in multiple countries, and most of my international travel revolves around birding. eBird is an excellent resource for bird records. The availability of absence data, abundance data, and effort data in checklists make eBird data particularly powerful for understanding species occurrence.

See my [eBird profile](https://ebird.org/profile/ODIwMjUz/world).

## Bird counts, dragonfly counts, and butterfly counts

I have participated in Christmas Bird Counts for years, usually in an area leader/co-leader role. I have also participated in Important Bird Area counts as an area leader/co-leader and contributed census data to the Vaseux Lake Bird Observatory.

I have participated in many dragonfly counts and butterfly counts in Ontario (Algonquin, Haliburton, Hamilton).
