project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    title: Nathan G. Earley
    left:
      - text: Research & Publications
        href: research/index.qmd
        icon: book
      - text: Education
        href: education/index.qmd
        icon: mortarboard
      - text: Teaching
        href: teaching/index.qmd
        icon: bus-front
      - text: Community Science
        href: community_science/index.qmd
        icon: binoculars
    tools:
      - icon: github
        href: "https://github.com/earley-birder"
      
format:
  html:
    theme: [cosmo, styles.scss]

