---
title: Education
---

Note: This site is currently under development.

## PhD student (September 2022 - present)

Ecology (Environmental Studies) \| University of Victoria \| British Columbia, Canada

**Thesis title**: "Mobilizing species occurrence data for conservation prioritization"

Supervised by [Brian M. Starzomski](https://biodiversity.uvic.ca/) (UVic)

## MSc (September 2020 - August 2022)

Biology \| University of British Columbia \| British Columbia, Canada

**Thesis title**: "Host specificity and ovipositor characteristics of adventive parasitoids proposed for the biological control of *Drosophila suzukii*"

Co-supervised by [Chandra E. Moffat](https://scholar.google.ca/citations?user=4vsRoJkAAAAJ&hl=en) (AAFC) and [Robert G. Lalonde](https://scholar.google.com./citations?user=3INkjiMAAAAJ&hl=en) (UBC)

## BSc (September 2015 - June 2019)

Zoology (Hons.) \| University of British Columbia \| British Columbia, Canada \| 

**Honours thesis title**: "Species composition of the parasitoid genus *Eurytoma* (Hymenoptera: Eurytomidae) varies at a local scale in *Diplolepis variabilis* (Hymenoptera: Cynipidae) galls"

Supervised by [Robert G. Lalonde](https://scholar.google.com./citations?user=3INkjiMAAAAJ&hl=en) (UBC)

**Directed studies title**: "The party avoidance hypothesis: Remote sensing vertebrate diversity and habitat use in campus green spaces."

Supervised by [Adam T. Ford](https://atford.weebly.com/) (UBC)

## Other

WaspID Course \| Pennsylvania State University (2022)

Field Entomology \| Western Ghats, India \| University of Guelph (2018)

Ontario Scholar and French Immersion Certificate \| Ontario, Canada
